warning_threshold: 15

excluded:
  - Pods
  - "*/AppDelegate.swift"

disabled_rules:
  - trailing_whitespace
  - cyclomatic_complexity
  - unused_optional_binding

line_length:
  warning: 200

file_length:
  warning: 500

function_body_length:
  warning: 90
  error: 120

function_parameter_count:
  warning: 6
  error: 10

identifier_name:
  min_length: 1

vertical_whitespace:
  max_empty_lines: 2

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  ignores_case_statements: true
  warning: 12
  error: 20